=== sotalya/tucuxi-core/test/data/queries/xml_query.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<!-- ##################################################################### -->
<!-- XML Schema Definition -->
<!-- ##################################################################### -->

<xs:element name="query">
	<xs:complexType>
		<xs:sequence>
			<xs:element name="queryID" type="xs:string" />
			<xs:element name="clientID" type="xs:unsignedInt" />
			<xs:element name="date" type="xs:dateTime" />
			<xs:element name="language">
				<xs:simpleType>
					<!-- As seen in Tucux's DataType Enum -->
					<xs:restriction base="xs:string">
						<xs:enumeration value="en" />
						<xs:enumeration value="fr" />
						<xs:enumeration value="de" />
						<xs:enumeration value="it" />
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="admin" type="adminType" minOccurs="0" />
			<xs:element name="parameters" type="parametersType" />
			<xs:element name="requests">
			<xs:complexType>
		        <xs:sequence>
		          <xs:element name="request" type="requestType" maxOccurs="unbounded" />
		        </xs:sequence>
			</xs:complexType>
		</xs:element>
		</xs:sequence>
		<xs:attribute name="version" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:string">
				 	<!-- Version number beginning and ending with a number, 
				 	each number being separated by a dot -->
			     	<xs:pattern value="(((\d+)+\.)+)?(\d+)" />
			    </xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
</xs:element>

<!-- ##################################################################### -->
<!-- Global types for administrative informations -->
<!-- ##################################################################### -->

<!-- Everything is optional in this type -->
<xs:complexType name="adminType">
	<xs:sequence>
		<xs:element name="mandator" minOccurs="0">
			<xs:complexType>
				<xs:sequence>
					<xs:element name="person" minOccurs="0">
						<xs:complexType>
							<xs:sequence>
								<xs:element name="id" type="xs:string" minOccurs="0" />
								<xs:element name="title" type="xs:string" minOccurs="0" />
								<xs:element name="firstName" type="xs:string" minOccurs="0" />
								<xs:element name="lastName" type="xs:string" minOccurs="0" />
								<xs:group ref="contactGroup" minOccurs="0" />
							</xs:sequence>
						</xs:complexType>
					</xs:element>
					<xs:element name="institute" type="instituteType" minOccurs="0" />
				</xs:sequence>
			</xs:complexType>
		</xs:element>
		<xs:element name="patient" minOccurs="0">
			<xs:complexType>
				<xs:sequence>
					<xs:element name="person" minOccurs="0">
						<xs:complexType>
							<xs:sequence>
								<xs:element name="id" type="xs:string" minOccurs="0" />
								<xs:element name="firstName" type="xs:string" minOccurs="0" />
								<xs:element name="middleName" type="xs:string" minOccurs="0" />
								<xs:element name="lastName" type="xs:string" minOccurs="0" />
								<xs:element name="birthdate" type="xs:dateTime" minOccurs="0" />
								<xs:element name="gender" type="xs:string" minOccurs="0" />
								<xs:element name="hospitalStayNumber" type="xs:string" minOccurs="0" />
								<xs:group ref="contactGroup" minOccurs="0" />
							</xs:sequence>
						</xs:complexType>
					</xs:element>
					<xs:element name="institute" type="instituteType" minOccurs="0" />
				</xs:sequence>
			</xs:complexType>
		</xs:element>
		<xs:element name="clinicalData" minOccurs="0">
			<xs:complexType>
				<xs:sequence>
					<xs:any processContents="skip" maxOccurs="unbounded" />
				</xs:sequence>
			</xs:complexType>
		</xs:element>
	</xs:sequence>
</xs:complexType>

<xs:complexType name="instituteType">
	<xs:sequence>
		<xs:element name="id" type="xs:string" minOccurs="0" />
		<xs:element name="name" type="xs:string" minOccurs="0" />
		<xs:group ref="contactGroup" minOccurs="0" />
	</xs:sequence>
</xs:complexType>

<xs:complexType name="addressType">
	<xs:sequence>
		<xs:element name="street" type="xs:string" minOccurs="0" />
		<xs:element name="postCode" minOccurs="0">
			<xs:simpleType>
				 <xs:restriction base="xs:string">
				 	<!-- 4 digit number that can't begin with a 0 -->
			     	<xs:pattern value="[1-9]([0-9]{3})" />
			    </xs:restriction>
			</xs:simpleType>
		</xs:element>
		<xs:element name="city" type="xs:string" minOccurs="0" />
		<xs:element name="state" type="xs:string" minOccurs="0" />
		<xs:element name="country" type="xs:string" minOccurs="0" />
	</xs:sequence>
</xs:complexType>

<xs:complexType name="phoneType">
	<xs:sequence>
		<!-- Number hasn't a regex restriction because of other coutries phone numbers -->
		<xs:element name="number" type="xs:string" minOccurs="0" />
		<xs:element name="type" type="xs:string" minOccurs="0" />
	</xs:sequence>
</xs:complexType>

<xs:complexType name="emailType">
	<xs:sequence>
		<!-- Address hasn't a regex restriction because there's 
		a problem with meta characters for this particular regex -->
		<xs:element name="address" type="xs:string" minOccurs="0" />
		<xs:element name="type" type="xs:string" minOccurs="0" />
	</xs:sequence>
</xs:complexType>

<!-- ##################################################################### -->
<!-- Global groups for administrative informations -->
<!-- ##################################################################### -->

<xs:group name="contactGroup">
	<xs:sequence>
		<xs:element name="address" type="addressType" minOccurs="0" />
		<xs:element name="phone" type="phoneType" minOccurs="0" />
		<xs:element name="email" type="emailType" minOccurs="0" />
	</xs:sequence>
</xs:group>

<!-- ##################################################################### -->
<!-- Global types for query parameters -->
<!-- ##################################################################### -->

<xs:complexType name="parametersType">
	<xs:sequence>
		<xs:element name="patient">
			<xs:complexType>
				<xs:sequence>
					<xs:element name="covariates">
						<xs:complexType>
							<xs:sequence>
								<xs:element name="covariate" type="covariateType" maxOccurs="unbounded" />
							</xs:sequence>
						</xs:complexType>
					</xs:element>
				</xs:sequence>
			</xs:complexType>
		</xs:element>
		<xs:element name="drugs">
			<xs:complexType>
				<xs:sequence>
					<xs:element name="drug" type="drugType" maxOccurs="unbounded" />
				</xs:sequence>
			</xs:complexType>
		</xs:element>
	</xs:sequence>
</xs:complexType>

<xs:complexType name="covariateType">
	<xs:sequence>
		<xs:element name="name" type="xs:string" />
		<xs:element name="date" type="xs:dateTime" />
		<xs:element name="value" type="xs:string" />
		<xs:element name="unit" type="xs:string" />
		<xs:element name="dataType">
			<xs:simpleType>
				<!-- As seen in Tucux's DataType Enum -->
				<xs:restriction base="xs:string">
					<xs:enumeration value="Int" />
					<xs:enumeration value="Double" />
					<xs:enumeration value="Bool" />
					<xs:enumeration value="Date" />
				</xs:restriction>
			</xs:simpleType>
		</xs:element>
		<xs:element name="nature"  minOccurs="0">
			<xs:simpleType>
				<!-- As seen in the MOLIS specification -->
				<xs:restriction base="xs:string">
					<xs:enumeration value="continuous" />
					<xs:enumeration value="discrete" />
					<xs:enumeration value="categorical" />
				</xs:restriction>
			</xs:simpleType>
		</xs:element>
	</xs:sequence>
</xs:complexType>

<xs:complexType name="drugType">
	<xs:sequence>
		<xs:element name="drugID" type="xs:string" />
		<xs:element name="activePrinciple" type="xs:string" />
		<xs:element name="brandName" type="xs:string" />
		<xs:element name="atc" type="xs:string" />
		<xs:element name="treatment" type="treatmentType" />
		<xs:element name="samples" minOccurs="0">
			<xs:complexType>
		        <xs:sequence>
		          <xs:element name="sample" type="sampleType" maxOccurs="unbounded" />
		        </xs:sequence>
			</xs:complexType>
		</xs:element>
		<xs:element name="targets" minOccurs="0">
			<xs:complexType>
		        <xs:sequence>
		          <xs:element name="target" type="targetType" maxOccurs="unbounded" />
		        </xs:sequence>
			</xs:complexType>
		</xs:element>
	</xs:sequence>
</xs:complexType>

<xs:complexType name="treatmentType">
	<xs:sequence>
		<xs:element name="dosageHistory" type="dosageHistoryType" minOccurs="0" />
	</xs:sequence>
</xs:complexType>

<!-- This type and other linked types are made to be the most compatible 
with the DosageHistory class and AbstractDosage subclasses -->
<xs:complexType name="dosageHistoryType">
	<xs:sequence>
		<xs:element name="dosageTimeRange" type="dosageTimeRangeType" maxOccurs="unbounded" />
	</xs:sequence>
</xs:complexType>

<xs:complexType name="dosageTimeRangeType">
	<xs:sequence>
		<xs:group ref="dateIntervalGroup" />
		<xs:element name="dosage" type="dosageType" maxOccurs="unbounded" />
	</xs:sequence>
</xs:complexType>

<!-- Is the equivalent as the AbstractDosage class -->
<xs:complexType name="dosageType">
	<xs:choice>
		<xs:element name="dosageLoop" type="dosageLoopType" />
		<xs:group ref="dosageBoundedGroup" />
	</xs:choice>
</xs:complexType>

<xs:complexType name="dosageLoopType">
  <xs:sequence>
    <xs:group ref="dosageBoundedGroup" />
  </xs:sequence>
</xs:complexType>

<xs:complexType name="dosageRepeatType">
	<xs:sequence>
		<xs:element name="iterations">
			<xs:simpleType>
				<xs:restriction base="xs:int">
					<xs:minInclusive value="1" />
				</xs:restriction>
			</xs:simpleType>
		</xs:element>
		<xs:group ref="dosageBoundedGroup" />
	</xs:sequence>
</xs:complexType>

<xs:complexType name="dosageSequenceType">
	<xs:sequence>
		<xs:group ref="dosageBoundedGroup" maxOccurs="unbounded" />
	</xs:sequence>
</xs:complexType>

<xs:complexType name="lastingDosageType">
	<xs:sequence>
		<xs:element name="interval" type="xs:time" />
		<xs:group ref="intakeGroup" />
	</xs:sequence>
</xs:complexType>

<xs:complexType name="dailyDosageType">
	<xs:sequence>
		<xs:element name="time" type="xs:time" />
		<xs:group ref="intakeGroup" />
	</xs:sequence>
</xs:complexType>

<xs:complexType name="weeklyDosageType">
	<xs:sequence>
		<xs:element name="day">
		 	<xs:simpleType>
				<xs:restriction base="xs:int">
					<xs:minInclusive value="0" />
					<xs:maxInclusive value="6" />
				</xs:restriction>
			</xs:simpleType>
    	</xs:element>
		<xs:element name="time" type="xs:time" />
		<xs:group ref="intakeGroup" />
	</xs:sequence>
</xs:complexType>

<xs:complexType name="doseType">
	<xs:sequence>
		<xs:element name="value" type="xs:decimal" />
		<xs:element name="unit" type="xs:string" />
		<xs:element name="infusionTimeInMinutes" type="xs:decimal" minOccurs="0"/>
	</xs:sequence>
</xs:complexType>

<xs:complexType name="formulationAndRouteType">
	<xs:sequence>
		<xs:element name="formulation">
			<xs:simpleType>
				<!-- This enumeration is based on the one present in formulationandroute.h file in Tucuxi -->
				<xs:restriction base="xs:string">
		            <xs:enumeration value="Undefined" />
		            <xs:enumeration value="ParenteralSolution" />
		            <xs:enumeration value="OralSolution" />
		            <xs:enumeration value="Test" />
		        </xs:restriction>
			</xs:simpleType>
		</xs:element>
		<xs:element name="administrationName" type="xs:string" />
		<xs:element name="administrationRoute">
			<xs:simpleType>
				<!-- This enumeration is based on the one present in formulationandroute.h file in Tucuxi -->
				<xs:restriction base="xs:string">
		            <xs:enumeration value="Undefined" />
		            <xs:enumeration value="Intramuscular" />
		            <xs:enumeration value="IntravenousBolus" />
		            <xs:enumeration value="IntravenousDrip" />
		            <xs:enumeration value="Nasal" />
		            <xs:enumeration value="Oral" />
		            <xs:enumeration value="Rectal" />
		            <xs:enumeration value="Subcutaneous" />
		            <xs:enumeration value="Sublingual" />
		            <xs:enumeration value="Transdermal" />
		            <xs:enumeration value="Vaginal" />
		        </xs:restriction>
			</xs:simpleType>
		</xs:element>
		<xs:element name="absorbtionModel">
			<xs:simpleType>
				<!-- This enumeration is based on the one present in definitions.h file in Tucuxi -->
				<xs:restriction base="xs:string">
		            <xs:enumeration value="Undefined" />
		            <xs:enumeration value="Intravascular" />
		            <xs:enumeration value="Extravascular" />
		            <xs:enumeration value="Infusion" />
		        </xs:restriction>
			</xs:simpleType>
		</xs:element>
	</xs:sequence>
</xs:complexType>

<xs:complexType name="sampleType">
	<xs:sequence>
		<xs:element name="sampleID" type="xs:positiveInteger"/>
		<xs:element name="sampleDate" type="xs:dateTime" />
		<xs:element name="arrivalDate" type="xs:dateTime" />
		<xs:element name="concentrations">
	      	<xs:complexType>
		        <xs:sequence>
		          	<xs:element name="concentration" maxOccurs="unbounded">
				      	<xs:complexType>
				        	<xs:sequence>
				          		<xs:element name="analyteID" type="xs:string" />
					          	<xs:element name="value" type="xs:decimal" />
					          	<xs:element name="unit" type="xs:string" />
				        	</xs:sequence>
				      	</xs:complexType>
					</xs:element>
		        </xs:sequence>
	      	</xs:complexType>
		</xs:element>
		<xs:element name="likelyhoodUse" type="xs:boolean" minOccurs="0"/>
	</xs:sequence>
</xs:complexType>

<xs:complexType name="targetType">
	<xs:sequence>
		<xs:element name="activeMoietyID" type="xs:string" />
		<xs:element name="targetType">
			<xs:simpleType>
				<!-- This enumeration is based on the one present in the drug file's XSD -->
				<xs:restriction base="xs:string">
		            <xs:enumeration value="peak" />
		            <xs:enumeration value="residual" />
		            <xs:enumeration value="mean" />
		            <xs:enumeration value="auc" />
		            <xs:enumeration value="aucOverMic" /> <!-- In that case MIC should be a covariate -->
		            <xs:enumeration value="timeOverMic" /> <!-- In that case MIC should be a covariate -->
		            <xs:enumeration value="aucDividedByMic" /> <!-- In that case MIC should be a covariate -->
		            <xs:enumeration value="peakDividedByMic" /> <!-- In that case MIC should be a covariate -->
		        </xs:restriction>
			</xs:simpleType>
		</xs:element>
		<xs:element name="unit" type="xs:string" />
		<xs:element name="inefficacyAlarm" type="xs:decimal" />
		<xs:element name="min" type="xs:decimal" />
		<xs:element name="best" type="xs:decimal" />
		<xs:element name="max" type="xs:decimal" />
		<xs:element name="toxicityAlarm" type="xs:decimal" />
	</xs:sequence>
</xs:complexType>

<xs:complexType name="dateIntervalType">
	<xs:sequence>
		<xs:group ref="dateIntervalGroup" />
	</xs:sequence>
</xs:complexType>

<xs:complexType name="percentilesType">
	<xs:sequence>
		<xs:element name="percentile" maxOccurs="unbounded">
			<xs:simpleType>
				<xs:restriction base="xs:double">
					<xs:minInclusive value="0" />
					<xs:maxInclusive value="100" />
				</xs:restriction>
			</xs:simpleType>
		</xs:element>
	</xs:sequence>
</xs:complexType>

<xs:complexType name="graphType">
	<xs:sequence>
		<xs:element name="dateInterval" type="dateIntervalType" />
		<xs:element name="percentiles" type="percentilesType" />
	</xs:sequence>
</xs:complexType>

<!-- ##################################################################### -->
<!-- Global groups for query parameters -->
<!-- ##################################################################### -->

<xs:group name="dateIntervalGroup">
	<xs:sequence>
		<xs:element name="start" type="xs:dateTime" />
		<xs:element name="end" type="xs:dateTime" />
	</xs:sequence>
</xs:group>

<xs:group name="dosageBoundedGroup">
	<xs:choice>
		<xs:element name="dosageRepeat" type="dosageRepeatType" />
		<xs:element name="dosageSequence" type="dosageSequenceType" />
		<xs:choice>
			<xs:element name="lastingDosage" type="lastingDosageType" />
			<xs:element name="dailyDosage" type="dailyDosageType" />
			<xs:element name="weeklyDosage" type="weeklyDosageType" />
		</xs:choice>
	</xs:choice>
</xs:group>

<xs:group name="intakeGroup">
	<xs:sequence>
		<xs:element name="dose" type="doseType" />
		<xs:element name="formulationAndRoute" type="formulationAndRouteType" />
	</xs:sequence>
</xs:group>

<!-- ##################################################################### -->
<!-- Global types for requests -->
<!-- ##################################################################### -->

<xs:complexType name="requestType">
	<xs:sequence>
		<xs:element name="requestID" type="xs:string" />
		<xs:element name="drugID" type="xs:string" />
		<xs:element name="drugModelID" type="xs:string" minOccurs="0"/>
		<xs:element name="requestType">
			<xs:simpleType>
				<xs:restriction base="xs:string">
		            <xs:enumeration value="prediction" />
		            <xs:enumeration value="firstDosage" />
		            <xs:enumeration value="dosageRisk" />
		            <xs:enumeration value="dosageLikelyhood" />
		            <xs:enumeration value="dosageAdaptation" />
		            <xs:enumeration value="sampleDate" />
		            <xs:enumeration value="backextrapolation:dosageSearch" />
		            <xs:enumeration value="backextrapolation:dateSearch" />
		            <xs:enumeration value="sampleDate" />
		            <xs:enumeration value="report" />
		        </xs:restriction>
			</xs:simpleType>
		</xs:element>
		<xs:element name="nbPointsPerHour" type="xs:int" minOccurs="0" />
		<xs:element name="dateInterval" type="dateIntervalType" minOccurs="0" />
		<xs:element name="predictionType" minOccurs="0">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="population" />
					<xs:enumeration value="a priori" />
					<xs:enumeration value="a posteriori" />
					<xs:enumeration value="best" />
				</xs:restriction>
			</xs:simpleType>
		</xs:element>
		<xs:element name="graph" type="graphType" minOccurs="0" />
		<xs:element name="percentiles" type="percentilesType" minOccurs="0" />
		<xs:element name="backextrapolation" minOccurs="0">
			<xs:complexType>
				<xs:choice>
					<xs:group ref="BE_dosageSearchGroup" />
					<xs:group ref="BE_dateSearchGroup" />
				</xs:choice>
			</xs:complexType>
		</xs:element>
	</xs:sequence>
</xs:complexType>

<!-- ##################################################################### -->
<!-- Global groups for requests -->
<!-- ##################################################################### -->

<xs:group name="BE_dosageSearchGroup">
	<xs:sequence>
		<xs:element name="sample" type="sampleType" />
	</xs:sequence>
</xs:group>

<xs:group name="BE_dateSearchGroup">
	<xs:sequence>
		<xs:element name="incompleteSample">
			<xs:complexType>
				<xs:sequence>
					<xs:element name="sampleID" type="xs:positiveInteger"/>
					<xs:element name="arrivalDate" type="xs:dateTime" />
					<xs:element name="concentrations">
				      	<xs:complexType>
					        <xs:sequence>
					          	<xs:element name="concentration" maxOccurs="unbounded">
							      	<xs:complexType>
							        	<xs:sequence>
							          		<xs:element name="analyteID" type="xs:string" />
								          	<xs:element name="value" type="xs:decimal" />
								          	<xs:element name="unit" type="xs:string" />
							        	</xs:sequence>
							      	</xs:complexType>
								</xs:element>
					        </xs:sequence>
				      	</xs:complexType>
					</xs:element>
					<xs:element name="likelyhoodUse" type="xs:boolean" minOccurs="0"/>
				</xs:sequence>
			</xs:complexType>
		</xs:element>
		<xs:element name="dosage" type="dosageType" />
	</xs:sequence>
</xs:group>

</xs:schema>

=== sotalya/tucuxi-core/test/data/queries/test_imatinib_percentiles.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<query version="1.0" 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="xml_query.xsd">
	
	<queryID>imatinib_1</queryID>
	<clientID>124568</clientID>
	<date>2018-07-11T13:45:30</date> <!-- Date the xml has been sent -->
	<language>en</language>
	<!-- Administrative informations -->
	<admin>
		<!-- Informations relative to the mandator -->
		<mandator>
			<!-- Mandator's personal informations -->
			<person>
			  <id>asdf</id>
				<title>Dr.</title>
				<firstName>John</firstName>
				<lastName>Doe</lastName>
				<address>
					<street>Av. de l'Ours 2</street>
					<postCode>1010</postCode>
					<city>Lausanne</city>
					<state>Vaud</state>
					<country>Suisse</country>
				</address>
				<phone>
					<number>0213140002</number>
					<type>work</type>
				</phone>
				<email>
					<address>john.doe@chuv.com</address>
					<type>professional</type>
				</email>
			</person>
			<!-- Mandator's institute informations -->
			<institute>
				<id>456789</id>
				<name>CHUV</name>
				<address>
					<street>Av. de l'Ours 1</street>
					<postCode>1010</postCode>
					<city>Lausanne</city>
					<state>Vaud</state>
					<country>Suisse</country>
				</address>
				<phone>
					<number>0213140001</number>
					<type>work</type>
				</phone>
				<email>
					<address>info@chuv.com</address>
					<type>professional</type>
				</email>
			</institute>
		</mandator>
		<!-- Informations relative to the patient -->
		<patient>
			<!-- Patient's personal informations -->
			<person>
				<id>123456</id>
				<firstName>Alice</firstName>
				<middleName></middleName>
				<lastName>Aupaysdesmerveilles</lastName>
				<birthdate>1970-01-01T00:00:00</birthdate>
				<gender>Woman</gender>
				<hospitalStayNumber>1337</hospitalStayNumber>
				<address>
					<street>Av. d'Ouchy 27</street>
					<postCode>1006</postCode>
					<city>Lausanne</city>
					<state>Vaud</state>
					<country>Suisse</country>
				</address>
				<phone>
					<number>0216170002</number>
					<type>work</type>
				</phone>
				<email>
					<address>alice.apdm@gmail.com</address>
					<type>private</type>
				</email>
			</person>
			<!-- Patient's institute informations -->
			<institute>
				<id>456789</id>
				<name>CHUV</name>
		        <address>
		          <street>Av. de l'Ours 1</street>
		          <postCode>1010</postCode>
		          <city>Lausanne</city>
		          <state>Vaud</state>
		          <country>Suisse</country>
		        </address>
				<phone>
					<number>0213140001</number>
					<type>work</type>
				</phone>
				<email>
					<address>info@chuv.com</address>
					<type>professional</type>
				</email>
			</institute>
		</patient>
		<clinicalData>
			<date>2018-07-11T13:45:30</date>
			<name>lastcreatinine</name>
			<diagnosis>lorem ipsum</diagnosis>
			<toxicity>lorem ipsum</toxicity>
			<indication>lorem ipsum</indication>
			<response>lorem ipsum</response>
			<value>80.0</value>
		</clinicalData>
	</admin>
	<parameters>
		<!-- All the information regarding the patient -->
		<patient>
	        <covariates> <!--
	        	<covariate>
	        		<name>birthdate</name>
	        		<date>2018-07-11T10:45:30</date>
	        		<value>1990-01-01T00:00:00</value>
	        		<unit></unit>
              		<dataType>Date</dataType>
	        		<nature>discrete</nature>
	        	</covariate> -->
	        	<covariate>
	        		<name>bodyweight</name>
	        		<date>2018-07-11T10:45:30</date>
	        		<value>40</value>
	        		<unit>kg</unit>
              		<dataType>Double</dataType>
	        		<nature>discrete</nature>
	        	</covariate>
	        </covariates>
	    </patient>
	    <!-- List of the drugs informations we have concerning the patient -->
	    <drugs>
	    	<!-- All the information regarding the drug -->
	    	<drug>
		    	<drugID>imatinib</drugID>
		    	<activePrinciple>something</activePrinciple>
		    	<brandName>somebrand</brandName>
		    	<atc>something</atc>
		    	<!-- All the information regarding the treatment -->
		    	<treatment>
			    	<dosageHistory>
			    		<dosageTimeRange>
			    			<start>2018-07-06T13:45:30</start>
					    	<end>2018-07-08T13:45:30</end>
					    	<dosage>
					    		<dosageLoop>
						    		<dailyDosage>
						    			<time>12:00:00</time>
						    			<dose>
							        		<value>250</value>
							        		<unit>mg</unit>
							        		<infusionTimeInMinutes>60</infusionTimeInMinutes>
							        	</dose>
							        	<formulationAndRoute>
							        		<formulation>ParenteralSolution</formulation>
							        		<administrationName>foo bar</administrationName>
							        		<administrationRoute>IntravenousBolus</administrationRoute>
							        		<absorbtionModel>Extravascular</absorbtionModel>
							        	</formulationAndRoute>
						    		</dailyDosage>
					    		</dosageLoop>
					    	</dosage>
			    		</dosageTimeRange>
			    	</dosageHistory>
			    </treatment>
			    <!-- Samples history -->
			    <samples>
			    	<sample>
			    		<sampleID>123456</sampleID>
			    		<sampleDate>2018-07-07T20:00:00</sampleDate>
			    		<arrivalDate>2018-07-07T22:00:00</arrivalDate>
			    		<concentrations>
			    			<concentration>
				    			<analyteID>imatinib</analyteID>
				    			<value>1.0</value>
				    			<unit>mg/l</unit>
				    		</concentration>
			    		</concentrations>
			    	</sample>
			    </samples>
			    <!-- Personalised targets -->
			    <targets>
			    	<!-- It's the same node we can find in the drug model xml file -->
			    	<target>
			    		<activeMoietyID>imatinib</activeMoietyID>
			    		<targetType>residual</targetType>
			    		<unit>mg</unit>
			            <inefficacyAlarm>15</inefficacyAlarm>
			            <min>20</min>
			            <best>25</best>
			            <max>30</max>
			            <toxicityAlarm>50</toxicityAlarm>
			    	</target>
		    	</targets>
		    </drug>
	    </drugs>
	</parameters>
	<!-- List of the requests we want the server to take care of -->
	<requests>
		<request>
			<!-- The options of the requests are subnodes of the request node -->
			<!-- Everything is optional except the request type -->
			<!-- We use default values if the option isn't given -->
			<requestID>population_1</requestID>
			<drugID>imatinib</drugID>
			<requestType>prediction</requestType>
			<dateInterval>
	    		<start>2018-07-06T13:45:30</start>
	    		<end>2018-07-08T13:45:30</end>
	    	</dateInterval>
	    	<predictionType>population</predictionType>
	    	<graph>
	    		<dateInterval>
		    		<start>2018-07-11T13:45:30</start>
		    		<end>2018-07-12T13:45:30</end>
		    	</dateInterval>
	    		<percentiles>
		    		<percentile>50</percentile>
		    	</percentiles>
	    	</graph>
	    	<percentiles>
	    		<percentile>5</percentile>
	    		<percentile>10</percentile>
	    		<percentile>25</percentile>
	    		<percentile>50</percentile>
	    		<percentile>75</percentile>
	    		<percentile>90</percentile>
	    		<percentile>95</percentile>
	    	</percentiles>
		</request>
		
		<request>
			<requestID>apriori_1</requestID>
			<drugID>imatinib</drugID>
			<requestType>prediction</requestType>
			<dateInterval>
	    		<start>2018-07-06T13:45:30</start>
	    		<end>2018-07-08T13:45:30</end>
	    	</dateInterval>
	    	<predictionType>a priori</predictionType>
	    	<graph>
	    		<dateInterval>
		    		<start>2018-07-11T13:45:30</start>
		    		<end>2018-07-12T13:45:30</end>
		    	</dateInterval>
	    		<percentiles>
		    		<percentile>50</percentile>
		    	</percentiles>
	    	</graph>
	    	<percentiles>
	    		<percentile>5</percentile>
	    		<percentile>10</percentile>
	    		<percentile>25</percentile>
	    		<percentile>50</percentile>
	    		<percentile>75</percentile>
	    		<percentile>90</percentile>
	    		<percentile>95</percentile>
	    	</percentiles>
		</request>
		
		<request>
			<requestID>aposteriori_1</requestID>
			<drugID>imatinib</drugID>
			<requestType>prediction</requestType>
			<dateInterval>
	    		<start>2018-07-06T13:45:30</start>
	    		<end>2018-07-08T13:45:30</end>
	    	</dateInterval>
	    	<predictionType>a posteriori</predictionType>
	    	<graph>
	    		<dateInterval>
		    		<start>2018-07-11T13:45:30</start>
		    		<end>2018-07-12T13:45:30</end>
		    	</dateInterval>
	    		<percentiles>
		    		<percentile>50</percentile>
		    	</percentiles>
	    	</graph>
	    	<percentiles>
	    		<percentile>5</percentile>
	    		<percentile>10</percentile>
	    		<percentile>25</percentile>
	    		<percentile>50</percentile>
	    		<percentile>75</percentile>
	    		<percentile>90</percentile>
	    		<percentile>95</percentile>
	    	</percentiles>
		</request>

	</requests>
</query>
